spring:
  datasource:
    url: jdbc:postgresql://postgres.scaffoldops.svc.cluster.local:5432/generatorapidb
    username: ${DB_USER:generatorapiuser}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
