apiVersion: v1
kind: ConfigMap
metadata:
  name: generator-api-config
  namespace: scaffoldops
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "generator-api-db-service"
  DB_PORT: "5432"
  DB_NAME: "generatorapidb"
  LOG_LEVEL: "INFO"
