apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generator-api-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
