apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-api-deployment
  namespace: scaffoldops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator-api
  template:
    metadata:
      labels:
        app: generator-api
    spec:
      volumes:
        - name: generator-api-config-volume
          configMap:
            name: generator-api-config
      containers:
        - name: generator-api
          image: scaffoldops/generator-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: generator-api-config-volume
              mountPath: /config/application.yml
              subPath: application.yml
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "optional:file:/config/"
            - name: SPRING_DATASOURCE_USERNAME
              value: "generatorapiuser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "generatorapipassword"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
